version: '3.8'

services:
  server:
    build: ./python-server/
    command: uvicorn python-server.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
  web-server:
    build: ./nodejs-server/ 
    command: npm run start
    volumes:
      - .:/app
    ports:
      - 9000:9000
  #client:
  #  build: ./nextjs-client/
  #  command: npm run start
  #  volumes:
  #    - .:/app
  #  ports:
  #    - 3000:3000
  #  depends_on:
  #    server:
  #      condition: service_started
  #    web-server: 
  #      condition: service_started